version: "3.4"

services:

  demo-db:
    build:
      context: ./demo-db
    env_file: .env
    environment:
       - POSTGRES_DB=postgres_demo
       - POSTGRES_PASSWORD=postgres_demo
    ports:
       - "${MAPPED_POSTGRES_PORT}:5432"

  ontop:
    #    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: ontop/ontop-endpoint:4.3.0-SNAPSHOT
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/fhir.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/omop.obda
      #      ONTOP_PROPERTIES_FILE: /opt/ontop/input/fhir.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/fhir.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      # ONTOP_DEV_MODE: "true"
      ONTOP_DEBUG: "true"
      ONTOP_DB_URL: ${ONTOP_DB_URL}
      ONTOP_DB_USER: ${ONTOP_DB_USER}
      ONTOP_DB_PASSWORD: ${ONTOP_DB_PASSWORD}
      ONTOP_DB_DRIVER: org.postgresql.Driver
    volumes:
      - ./input:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
#    entrypoint:
#      [
#        "/opt/wait-for-it/wait-for-it.sh",
#        "demo-db:5432",
#        "--timeout=0",
#        "--strict",
#        "--",
#        "/opt/ontop/entrypoint.sh",
#      ]
    ports:
      - "${MAPPED_ONTOP_PORT}:8080"